folder-structure/app2/config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :users
  resources :purchases
  resources :approvals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

folder-structure/app2/app/models/budget.rb
class Budget < ApplicationRecord
end

folder-structure/app2/app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[ show edit update destroy ]

  # GET /budgets or /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1 or /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully created." }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url, notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.fetch(:budget, {})
    end
end

folder-structure/app2/app/helpers/budgets_helper.rb
module BudgetsHelper
end

folder-structure/app2/app/views/budgets/_budget.html.erb
<div id="<%= dom_id budget %>">
</div>

folder-structure/app2/app/views/budgets/_form.html.erb
<%= form_with(model: budget) do |form| %>
  <% if budget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

folder-structure/app2/app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Show this budget", @budget %> |
  <%= link_to "Back to budgets", budgets_path %>
</div>

folder-structure/app2/app/views/budgets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Budgets</h1>

<div id="budgets">
  <% @budgets.each do |budget| %>
    <%= render budget %>
    <p>
      <%= link_to "Show this budget", budget %>
    </p>
  <% end %>
</div>

<%= link_to "New budget", new_budget_path %>

folder-structure/app2/app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Back to budgets", budgets_path %>
</div>

folder-structure/app2/app/views/budgets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budget %>

<div>
  <%= link_to "Edit this budget", edit_budget_path(@budget) %> |
  <%= link_to "Back to budgets", budgets_path %>

  <%= button_to "Destroy this budget", @budget, method: :delete %>
</div>