folder-structure/app2/config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :users
  resources :purchases
  resources :approvals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

folder-structure/app2/app/models/approval.rb
class Approval < ApplicationRecord
end

folder-structure/app2/app/controllers/approvals_controller.rb
# frozen_string_literal: true

# Controller
class ApprovalsController < ApplicationController
  before_action :set_approval, only: %i[show edit update destroy]

  # GET /approvals or /approvals.json
  def index
    @approvals = Approval.all
  end

  # GET /approvals/1 or /approvals/1.json
  def show; end

  # GET /approvals/new
  def new
    @approval = Approval.new
  end

  # GET /approvals/1/edit
  def edit; end

  # POST /approvals or /approvals.json
  def create
    @approval = Approval.new(approval_params)

    respond_to do |format|
      if @approval.save
        format.html { redirect_to approval_url(@approval), notice: 'Approval was successfully created.' }
        format.json { render :show, status: :created, location: @approval }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /approvals/1 or /approvals/1.json
  def update
    respond_to do |format|
      if @approval.update(approval_params)
        format.html { redirect_to approval_url(@approval), notice: 'Approval was successfully updated.' }
        format.json { render :show, status: :ok, location: @approval }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /approvals/1 or /approvals/1.json
  def destroy
    @approval.destroy

    respond_to do |format|
      format.html { redirect_to approvals_url, notice: 'Approval was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_approval
    @approval = Approval.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def approval_params
    params.fetch(:approval, {})
  end
end

folder-structure/app2/app/helpers/approvals_helper.rb
module ApprovalsHelper
end

folder-structure/app2/app/views/approvals/_approval.html.erb
<div id="<%= dom_id approval %>">
</div>

folder-structure/app2/app/views/approvals/_form.html.erb
<%= form_with(model: approval) do |form| %>
  <% if approval.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(approval.errors.count, "error") %> prohibited this approval from being saved:</h2>

      <ul>
        <% approval.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

folder-structure/app2/app/views/approvals/edit.html.erb
<h1>Editing approval</h1>

<%= render "form", approval: @approval %>

<br>

<div>
  <%= link_to "Show this approval", @approval %> |
  <%= link_to "Back to approvals", approvals_path %>
</div>

folder-structure/app2/app/views/approvals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Approvals</h1>

<div id="approvals">
  <% @approvals.each do |approval| %>
    <%= render approval %>
    <p>
      <%= link_to "Show this approval", approval %>
    </p>
  <% end %>
</div>

<%= link_to "New approval", new_approval_path %>

folder-structure/app2/app/views/approvals/new.html.erb
<h1>New approval</h1>

<%= render "form", approval: @approval %>

<br>

<div>
  <%= link_to "Back to approvals", approvals_path %>
</div>

folder-structure/app2/app/views/approvals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @approval %>

<div>
  <%= link_to "Edit this approval", edit_approval_path(@approval) %> |
  <%= link_to "Back to approvals", approvals_path %>

  <%= button_to "Destroy this approval", @approval, method: :delete %>
</div>